site_name: Axxes AWS Traineeship 2026

plugins:
- search
- git-revision-date-localized

theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

nav:
- Welcome: index.md
- Getting Started: content/getting-started/index.md
- Tagging: content/tagging/index.md
- Terraform Fundamentals: content/terraform-fundamentals/index.md
- EC2: content/ec2/index.md
- Networking: content/networking/index.md
- Terraform Modules: content/terraform-modules/index.md
- S3: content/s3/index.md
- IAM: content/iam/index.md
- DynamoDB: content/dynamodb/index.md
- Messaging: content/messaging/index.md
- ECS: content/ecs/index.md

markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: .
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- def_list
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.details
- pymdownx.tabbed:
    alternate_style: true
