apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  namespace: deboeck
  labels:
    owner: deboeck
spec:
  selector:
    matchLabels:
      app: secret-deployment
      owner: deboeck
  template:
    metadata:
      labels:
        app: secret-deployment
        owner: deboeck
    spec:
      containers:
      - name: init-pod
        image: busybox
        command: ["sh", "-c", 'while true; do echo "Hello World!"; sleep 30; done']
        env:
          - name: SECRET_VALUE
            valueFrom:
              secretKeyRef:
                name: deboeck-secret
                key: secret.txt
