apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: deboeck
  labels:
    owner: deboeck
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80